"""Increase length of string in DB Models

Revision ID: 27b51409e9c7
Revises: f4316204e9af
Create Date: 2021-03-26 22:48:35.659199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b51409e9c7'
down_revision = 'f4316204e9af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bank_details', 'account_no',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=64),
                    existing_nullable=True)
    op.alter_column('bank_details', 'ifsc_code',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=64),
                    existing_nullable=True)
    op.alter_column('media', 'type',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=256),
                    existing_nullable=True)
    op.alter_column('milestone', 'description',
                    existing_type=sa.VARCHAR(length=64),
                    type_=sa.String(length=256),
                    existing_nullable=True)
    op.alter_column('milestone', 'status',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=256),
                    existing_nullable=True)
    op.alter_column('orders', 'description',
                    existing_type=sa.VARCHAR(length=64),
                    type_=sa.String(length=256),
                    existing_nullable=True)
    op.alter_column('orders', 'name',
                    existing_type=sa.VARCHAR(length=128),
                    type_=sa.String(length=256),
                    existing_nullable=True)
    op.alter_column('orders', 'state',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=256),
                    existing_nullable=True)
    op.alter_column('product', 'description',
                    existing_type=sa.VARCHAR(length=512),
                    type_=sa.String(length=256),
                    existing_nullable=True)
    op.alter_column('product', 'min_size',
                    existing_type=sa.VARCHAR(length=128),
                    type_=sa.String(length=256),
                    existing_nullable=True)
    op.alter_column('product', 'name',
                    existing_type=sa.VARCHAR(length=128),
                    type_=sa.String(length=256),
                    existing_nullable=True)
    op.alter_column('product', 'price',
                    existing_type=sa.VARCHAR(length=128),
                    type_=sa.String(length=256),
                    existing_nullable=True)
    op.alter_column('tender', 'description',
                    existing_type=sa.VARCHAR(length=64),
                    type_=sa.String(length=256),
                    existing_nullable=True)
    op.alter_column('tender', 'name',
                    existing_type=sa.VARCHAR(length=128),
                    type_=sa.String(length=256),
                    existing_nullable=True)
    op.alter_column('tender', 'state',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=256),
                    existing_nullable=True)
    op.alter_column('user_shg', 'SHG_Name',
                    existing_type=sa.VARCHAR(length=128),
                    type_=sa.String(length=256),
                    existing_nullable=True)
    op.alter_column('user_shg', 'WAContact',
                    existing_type=sa.VARCHAR(length=13),
                    type_=sa.String(length=24),
                    existing_nullable=True)
    op.alter_column('user_shg', 'industry_type',
                    existing_type=sa.VARCHAR(length=128),
                    type_=sa.String(length=256),
                    existing_nullable=True)
    op.alter_column('user_shg', 'name',
                    existing_type=sa.VARCHAR(length=128),
                    type_=sa.String(length=256),
                    existing_nullable=False)
    op.alter_column('user_shg', 'order_size',
                    existing_type=sa.VARCHAR(length=128),
                    type_=sa.String(length=256),
                    existing_nullable=True)
    op.alter_column('user_shg', 'password',
                    existing_type=sa.VARCHAR(length=128),
                    type_=sa.String(length=256),
                    existing_nullable=False)
    op.alter_column('user_shg', 'phone',
                    existing_type=sa.VARCHAR(length=13),
                    type_=sa.String(length=24),
                    existing_nullable=True)
    op.alter_column('user_shg', 'prod_capacity',
                    existing_type=sa.VARCHAR(length=128),
                    type_=sa.String(length=256),
                    existing_nullable=True)
    op.alter_column('user_shg', 'username',
                    existing_type=sa.VARCHAR(length=128),
                    type_=sa.String(length=256),
                    existing_nullable=False)
    op.alter_column('user_sme', 'WAContact',
                    existing_type=sa.VARCHAR(length=13),
                    type_=sa.String(length=24),
                    existing_nullable=True)
    op.alter_column('user_sme', 'industry_type',
                    existing_type=sa.VARCHAR(length=128),
                    type_=sa.String(length=256),
                    existing_nullable=True)
    op.alter_column('user_sme', 'name',
                    existing_type=sa.VARCHAR(length=128),
                    type_=sa.String(length=256),
                    existing_nullable=False)
    op.alter_column('user_sme', 'password',
                    existing_type=sa.VARCHAR(length=128),
                    type_=sa.String(length=256),
                    existing_nullable=False)
    op.alter_column('user_sme', 'phone',
                    existing_type=sa.VARCHAR(length=13),
                    type_=sa.String(length=24),
                    existing_nullable=True)
    op.alter_column('user_sme', 'username',
                    existing_type=sa.VARCHAR(length=128),
                    type_=sa.String(length=256),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sme', 'username',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=128),
                    existing_nullable=False)
    op.alter_column('user_sme', 'phone',
                    existing_type=sa.String(length=24),
                    type_=sa.VARCHAR(length=13),
                    existing_nullable=True)
    op.alter_column('user_sme', 'password',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=128),
                    existing_nullable=False)
    op.alter_column('user_sme', 'name',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=128),
                    existing_nullable=False)
    op.alter_column('user_sme', 'industry_type',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=128),
                    existing_nullable=True)
    op.alter_column('user_sme', 'WAContact',
                    existing_type=sa.String(length=24),
                    type_=sa.VARCHAR(length=13),
                    existing_nullable=True)
    op.alter_column('user_shg', 'username',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=128),
                    existing_nullable=False)
    op.alter_column('user_shg', 'prod_capacity',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=128),
                    existing_nullable=True)
    op.alter_column('user_shg', 'phone',
                    existing_type=sa.String(length=24),
                    type_=sa.VARCHAR(length=13),
                    existing_nullable=True)
    op.alter_column('user_shg', 'password',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=128),
                    existing_nullable=False)
    op.alter_column('user_shg', 'order_size',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=128),
                    existing_nullable=True)
    op.alter_column('user_shg', 'name',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=128),
                    existing_nullable=False)
    op.alter_column('user_shg', 'industry_type',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=128),
                    existing_nullable=True)
    op.alter_column('user_shg', 'WAContact',
                    existing_type=sa.String(length=24),
                    type_=sa.VARCHAR(length=13),
                    existing_nullable=True)
    op.alter_column('user_shg', 'SHG_Name',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=128),
                    existing_nullable=True)
    op.alter_column('tender', 'state',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=True)
    op.alter_column('tender', 'name',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=128),
                    existing_nullable=True)
    op.alter_column('tender', 'description',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=64),
                    existing_nullable=True)
    op.alter_column('product', 'price',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=128),
                    existing_nullable=True)
    op.alter_column('product', 'name',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=128),
                    existing_nullable=True)
    op.alter_column('product', 'min_size',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=128),
                    existing_nullable=True)
    op.alter_column('product', 'description',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=512),
                    existing_nullable=True)
    op.alter_column('orders', 'state',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=True)
    op.alter_column('orders', 'name',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=128),
                    existing_nullable=True)
    op.alter_column('orders', 'description',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=64),
                    existing_nullable=True)
    op.alter_column('milestone', 'status',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=True)
    op.alter_column('milestone', 'description',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=64),
                    existing_nullable=True)
    op.alter_column('media', 'type',
                    existing_type=sa.String(length=256),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=True)
    op.alter_column('bank_details', 'ifsc_code',
                    existing_type=sa.String(length=64),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=True)
    op.alter_column('bank_details', 'account_no',
                    existing_type=sa.String(length=64),
                    type_=sa.VARCHAR(length=32),
                    existing_nullable=True)
    # ### end Alembic commands ###
