"""Add product table

Revision ID: 467fbc53cc8e
Revises: 859da35cea70
Create Date: 2021-03-17 02:15:04.161420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '467fbc53cc8e'
down_revision = '859da35cea70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=128), nullable=True),
                    sa.Column('description', sa.String(
                        length=512), nullable=True),
                    sa.Column('image_uri', sa.String(
                        length=128), nullable=True),
                    sa.Column('min_size', sa.String(
                        length=128), nullable=True),
                    sa.Column('price', sa.String(length=128), nullable=True),
                    sa.Column('shg_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['shg_id'], ['user_shg.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
