"""Add plan to Tender

Revision ID: 509716253f5d
Revises: 27b51409e9c7
Create Date: 2021-03-26 23:14:49.468991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509716253f5d'
down_revision = '27b51409e9c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('tender_plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'media', 'tender', ['tender_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('media_tender_plan_id_fkey',
                       'media', type_='foreignkey')
    op.drop_column('media', 'tender_plan_id')
    # ### end Alembic commands ###
