"""Add Whatsapp Contact

Revision ID: 6e4bae17a423
Revises: f658e322aa5d
Create Date: 2021-03-16 02:45:56.094868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e4bae17a423'
down_revision = 'f658e322aa5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_shg', sa.Column(
        'WAContact', sa.String(length=13), nullable=True))
    op.add_column('user_sme', sa.Column(
        'WAContact', sa.String(length=13), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sme', 'WAContact')
    op.drop_column('user_shg', 'WAContact')
    # ### end Alembic commands ###
