"""Add order_name and tender_name

Revision ID: 8b35ba861bd7
Revises: 467fbc53cc8e
Create Date: 2021-03-18 23:46:57.786609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b35ba861bd7'
down_revision = '467fbc53cc8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('name', sa.String(length=128), nullable=True))
    op.add_column('tender', sa.Column('name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tender', 'name')
    op.drop_column('orders', 'name')
    # ### end Alembic commands ###
