"""Add plan_uri to order

Revision ID: 9ed86656207e
Revises: d5e2dd5dbf41
Create Date: 2021-03-27 02:07:55.818950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed86656207e'
down_revision = 'd5e2dd5dbf41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('plan_uri', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'plan_uri')
    # ### end Alembic commands ###
