"""Add image_uri in user models

Revision ID: cb6e345648ac
Revises: 8b35ba861bd7
Create Date: 2021-03-19 00:06:01.803892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb6e345648ac'
down_revision = '8b35ba861bd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tender_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'tender', ['tender_id'], ['id'])
    op.add_column('user_shg', sa.Column('image_uri', sa.String(length=128), nullable=True))
    op.add_column('user_sme', sa.Column('image_uri', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_sme', 'image_uri')
    op.drop_column('user_shg', 'image_uri')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'tender_id')
    # ### end Alembic commands ###
