"""Plan URI as a string

Revision ID: d5e2dd5dbf41
Revises: 27b51409e9c7
Create Date: 2021-03-27 01:17:57.593294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5e2dd5dbf41'
down_revision = '27b51409e9c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tender', sa.Column('plan_uri', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tender', 'plan_uri')
    # ### end Alembic commands ###
