"""Add name field in milestone model

Revision ID: f4316204e9af
Revises: cf3cad8c07c9
Create Date: 2021-03-21 23:22:41.699829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4316204e9af'
down_revision = 'cf3cad8c07c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('milestone', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('milestone', 'name')
    # ### end Alembic commands ###
