"""Initial Schema

Revision ID: f658e322aa5d
Revises: 
Create Date: 2021-03-15 01:47:50.119217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f658e322aa5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ifsc_code', sa.String(length=32), nullable=True),
    sa.Column('account_no', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_shg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=True),
    sa.Column('industry_type', sa.String(length=32), nullable=True),
    sa.Column('prod_capacity', sa.String(length=32), nullable=True),
    sa.Column('order_size', sa.String(length=32), nullable=True),
    sa.Column('bank_details_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_details_id'], ['bank_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=True),
    sa.Column('industry_type', sa.String(length=32), nullable=True),
    sa.Column('bank_details_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_details_id'], ['bank_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bid_amount', sa.Integer(), nullable=True),
    sa.Column('shg_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shg_id'], ['user_shg.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('sme_id', sa.Integer(), nullable=True),
    sa.Column('shg_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shg_id'], ['user_shg.id'], ),
    sa.ForeignKeyConstraint(['sme_id'], ['user_sme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prev_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.String(length=32), nullable=True),
    sa.Column('skills', sa.String(length=32), nullable=True),
    sa.Column('shg_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shg_id'], ['user_shg.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('sme_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sme_id'], ['user_sme.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_shg_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('password', sa.String(length=32), nullable=False),
    sa.Column('aadhar_details', sa.String(length=32), nullable=True),
    sa.Column('contact', sa.String(length=32), nullable=True),
    sa.Column('skills', sa.String(length=32), nullable=True),
    sa.Column('shg_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shg_id'], ['user_shg.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('tender_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tender.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('milestone_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('tender_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['milestone_id'], ['milestone.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tender.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    op.drop_table('milestone')
    op.drop_table('user_shg_member')
    op.drop_table('tender')
    op.drop_table('prev_projects')
    op.drop_table('order')
    op.drop_table('bid')
    op.drop_table('user_sme')
    op.drop_table('user_shg')
    op.drop_table('bank_details')
    # ### end Alembic commands ###
